### ISSUE TITLE
请问您的aecium怎么编译成MIPS下的程序呢？

### ISSUE THREAD

**Issue by ghost** [Red54/aecium#2]
学校里用的一直都是安腾客户端认证宽带，搜到好多资料发现aecium可以在linux下给安腾认证。想在openwrt下安装，可是不懂怎么把这个代码编译成openwrt的程序呢？路由器是MIPS的处理器，还不是ARM的。
我按照恩山上的教程装好了MinGW跟MSYS，不懂怎么用额。。。
新人一枚，还请赐教~万谢！

**Comment by Red54** [comment]
./configure的时候指定对应的--host和CC就可以了。

然后要注意路由器主控芯片是大端还是小端，
一般MTK/Ralink和Broadcom的是小端，
Qualcomm/Atheros的是大端。

你可以参考一下这个库的说明：
https://github.com/acgotaku/Ahnu-auth

不好意思，我现在才看到，因为我毕业后Unwatch了这个库。
